services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=iot_user
      - DB_PASSWORD=aha987
      - DB_NAME=weather_iot
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U iot_user -d weather_iot" ]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=iot_user
      - POSTGRES_PASSWORD=aha987
      - POSTGRES_DB=weather_iot
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge